### PR TITLE
tests: add generalized_object integration test

### PR DESCRIPTION
**Pull request by yoursunny**
This commit also enables pytest on Travis CI.

### CODE REVIEW

**Comment by yoursunny** [comment]
This is one of my three submissions to [Fixvember](https://codefresh.io/fixvember/), under category "create automated pipeline" and "improve testing".

CI build log: https://travis-ci.com/yoursunny/PyCNL/builds/91810457

**Comment by jefft0** [comment]
Hi Junxiao. The API for PyCNL is still under development and changing rapidly, especially the GeneralizedObjectHandler. I'm not sure we should add an integration test for something that could break soon. Can we wait a little while?

**Comment by yoursunny** [comment]
This is the simplest possible test that matches the example. Code and test should always be updated together.

**Comment by yoursunny** [comment]
> I'm not sure we should add an integration test for something that could break soon.

The same logic applies to the example. So should the example be removed?

**Comment by yoursunny** [comment]
Hey @jefft0, are we ready to move forward with adding this test case?

**Comment by jefft0** [comment]
Not quite yet ready. The API was changing rapidly during the AR project at the end of the year. We need to have a meeting to review the application experience with the API.

**Comment by yoursunny** [comment]
Hey @jefft0, are we ready to move forward with adding this test case?

**Pull request closed without merging**
